version: '3.8'

services:
  # PHP Rust 扩展开发环境
  php-rust-dev:
    build: .
    container_name: php-rust-extension-dev
    volumes:
      # 挂载当前目录到容器中，方便开发
      - .:/app
      # 挂载 Rust 缓存目录，避免重复下载依赖
      - rust-cache:/root/.cargo
    working_dir: /app
    # 保持容器运行
    tty: true
    stdin_open: true
    # 环境变量
    environment:
      - RUST_BACKTRACE=1
      - CARGO_TARGET_DIR=/app/target
    
    # 开发命令
    command: /bin/bash

volumes:
  # Rust 缓存卷
  rust-cache: 